"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { BlogCategory } from "../types";
import { createBlogCategory, updateBlogCategory } from "../server/actions";

export function BlogCategoriesClient({ initial }: { initial: BlogCategory[] }) {
  const [items, setItems] = useState(initial); const [editing, setEditing] = useState<BlogCategory | null>(null); const [open, setOpen] = useState(false); const [nameAr, setNameAr] = useState(""); const [nameEn, setNameEn] = useState(""); const [slug, setSlug] = useState(""); const [sortOrder, setSortOrder] = useState("0"); const [isActive, setIsActive] = useState(true); const [error, setError] = useState("");
  function start(item?: BlogCategory) { setEditing(item ?? null); setOpen(true); setNameAr(item?.nameAr ?? ""); setNameEn(item?.nameEn ?? ""); setSlug(item?.slug ?? ""); setSortOrder(String(item?.sortOrder ?? 0)); setIsActive(item?.isActive ?? true); setError(""); }
  function close() { setOpen(false); setEditing(null); }
  async function save() { const input = { nameAr, nameEn, slug: slug || undefined, sortOrder: Number(sortOrder), isActive }; const result = editing ? await updateBlogCategory({ ...input, id: editing.id }) : await createBlogCategory(input); if (!result.success) setError(result.error.message); else { setItems((current) => editing ? current.map((item) => item.id === result.data.id ? result.data : item).sort((a, b) => a.sortOrder - b.sortOrder) : [...current, result.data].sort((a, b) => a.sortOrder - b.sortOrder)); close(); } }
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--primary)]">Content</p><h1 className="mt-1 text-2xl font-extrabold">Blog Categories</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Keep the learning topics clear and easy to browse.</p></div><Button onClick={() => start()}>New category</Button></div>{error && <p role="alert" className="rounded-md bg-[var(--destructive-subtle)] p-3 text-xs text-[var(--destructive)]">{error}</p>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item.id} className="rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-card)] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{item.nameEn}</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">{item.nameAr}</p></div><span className={`text-xs font-semibold ${item.isActive ? "text-[var(--success)]" : "text-[var(--text-muted)]"}`}>{item.isActive ? "Enabled" : "Disabled"}</span></div><p className="mt-4 text-xs text-[var(--text-muted)]">/{item.slug} · order {item.sortOrder}</p><button className="mt-4 text-xs font-semibold text-[var(--primary)]" onClick={() => start(item)}>Edit</button></article>)}</div>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-md rounded-[var(--radius-lg)] bg-[var(--surface-card)] p-5 shadow-xl"><h2 className="text-lg font-bold">{editing ? "Edit category" : "New category"}</h2><div className="mt-4 space-y-3"><label className="text-xs font-semibold">Arabic name<Input value={nameAr} onChange={(e) => setNameAr(e.target.value)} /></label><label className="text-xs font-semibold">English name<Input value={nameEn} onChange={(e) => setNameEn(e.target.value)} /></label><label className="text-xs font-semibold">Slug<Input value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="skills-development" /></label><label className="text-xs font-semibold">Order<Input type="number" value={sortOrder} onChange={(e) => setSortOrder(e.target.value)} /></label><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} /> Enabled</label></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={close}>Cancel</Button><Button onClick={() => void save()}>Save</Button></div></div></div>}</div>;
}
