import "server-only";
import { AppError, NotFoundError, ValidationError } from "@/core/errors";
import { failure, success, type Result } from "@/core/result";
import type { AuthorizationService } from "@/modules/identity/domain/services";
import type { UserId } from "@/modules/identity/types";
import { logger } from "@/server/logger";
import { createNotificationService, type NotificationService } from "@/modules/notifications/domain/service";
import type { OrderRepository } from "../infrastructure/repository";
import type { OrderDetails, OrderSummary } from "../types";
import { canTransitionOrderStatus } from "./rules";

function errorFor(error: unknown): AppError { const code = error instanceof Error ? error.message : "ORDER_OPERATION_FAILED"; const messages: Record<string, string> = { CART_EMPTY: "Your cart is empty.", ADDRESS_NOT_FOUND: "Please select one of your saved addresses.", PAYMENT_METHOD_UNAVAILABLE: "This payment method is not available.", PRODUCT_UNAVAILABLE: "One of the products in your cart is no longer available.", INSUFFICIENT_STOCK: "There is not enough stock for one of the products in your cart.", COUPON_PRICING_CHANGED: "Your coupon is no longer available at this price. Please review your updated order total.", ORDER_NOT_FOUND: "The order does not exist.", ORDER_STATE_CHANGED: "The order was updated by another request. Please refresh and try again." }; return new AppError(code, messages[code] ?? "The order could not be completed.", { cause: error }); }
export class OrderService {
  constructor(private readonly repository: OrderRepository, private readonly authorization: AuthorizationService, private readonly notifications: NotificationService = createNotificationService()) {}
  async placeOrder(customerId: UserId, addressId: string, paymentMethodId: string, currency: string, checkoutToken: string, paymentReference?: string, paymentNotes?: string): Promise<Result<OrderDetails, AppError>> { try { return success(await this.repository.placeOrder(customerId, addressId, paymentMethodId, currency, checkoutToken, paymentReference, paymentNotes)); } catch (error) { return failure(errorFor(error)); } }
  async getCustomerOrders(customerId: UserId): Promise<Result<OrderSummary[], AppError>> { try { return success(await this.repository.findCustomerOrders(customerId)); } catch (error) { return failure(errorFor(error)); } }
  async getCustomerOrder(customerId: UserId, orderNumber: string): Promise<Result<OrderDetails, AppError>> { try { const order = await this.repository.findCustomerOrder(customerId, orderNumber); return order ? success(order) : failure(new NotFoundError("ORDER", "Order does not exist.")); } catch (error) { return failure(errorFor(error)); } }
  async getAdminOrders(userId: UserId): Promise<Result<OrderSummary[], AppError>> { const allowed = await this.authorization.requirePermission(userId, "orders.view"); if (!allowed.success) return failure(allowed.error); try { return success(await this.repository.findAdminOrders()); } catch (error) { return failure(errorFor(error)); } }
  async getAdminOrder(userId: UserId, orderId: string): Promise<Result<OrderDetails, AppError>> { const allowed = await this.authorization.requirePermission(userId, "orders.view"); if (!allowed.success) return failure(allowed.error); try { const order = await this.repository.findAdminOrder(orderId); return order ? success(order) : failure(new NotFoundError("ORDER", "Order does not exist.")); } catch (error) { return failure(errorFor(error)); } }
  async updateStatus(userId: UserId, orderId: string, status: OrderDetails["status"]): Promise<Result<OrderDetails, AppError>> { const allowed = await this.authorization.requirePermission(userId, "orders.update"); if (!allowed.success) return failure(allowed.error); try { const current = await this.repository.findStatus(orderId); if (!current) return failure(new NotFoundError("ORDER", "Order does not exist.")); const shipmentStatus = await this.repository.findShipmentStatus(orderId); if (shipmentStatus && ["SHIPPED", "OUT_FOR_DELIVERY", "DELIVERED"].includes(status)) return failure(new ValidationError("Use the shipment workflow for physical delivery updates.")); if (!canTransitionOrderStatus(current, status)) return failure(new ValidationError(`Order cannot move from ${current} to ${status}.`)); const previousPayment = await this.repository.findPaymentStatus(orderId); const updated = await this.repository.updateStatus(orderId, current, status, userId); await this.notifyStatus(updated); if (previousPayment !== "PAID" && updated.paymentStatus === "PAID") await this.notifyPayment(updated, "PAID"); return success(updated); } catch (error) { return failure(errorFor(error)); } }
  async updatePaymentStatus(userId: UserId, orderId: string, status: OrderDetails["paymentStatus"], note?: string): Promise<Result<OrderDetails, AppError>> { const current = await this.repository.findPaymentStatus(orderId); if (!current) return failure(new NotFoundError("ORDER", "Order does not exist.")); const verificationChange = ["PAID", "FAILED"].includes(status) && ["PENDING", "PENDING_VERIFICATION"].includes(current); const allowed = await this.authorization.requirePermission(userId, verificationChange ? "payments.verify" : "payments.update"); if (!allowed.success) return failure(allowed.error); try { const updated = await this.repository.updatePaymentStatus(orderId, status, userId, note); if (status === "PAID" || status === "FAILED") await this.notifyPayment(updated, status); return success(updated); } catch (error) { return failure(errorFor(error)); } }
  private async notifyStatus(order: OrderDetails) { const result = await this.notifications.createOrderStatusNotification(order.customerId as UserId, order.id, order.orderNumber, order.status); if (!result.success) logger.warn("Customer order status notification was not created", { orderId: order.id, code: result.error.code }); }
  private async notifyPayment(order: OrderDetails, status: "PAID" | "FAILED") { const result = await this.notifications.createPaymentNotification(order.customerId as UserId, order.id, order.orderNumber, status); if (!result.success) logger.warn("Customer payment notification was not created", { orderId: order.id, code: result.error.code }); }
}
