import "server-only";
import { AppError, NotFoundError, ValidationError } from "@/core/errors";
import { failure, success, type Result } from "@/core/result";
import type { AuthorizationService } from "@/modules/identity/domain/services";
import type { UserId } from "@/modules/identity/types";
import { logger } from "@/server/logger";
import { createNotificationService, type NotificationService } from "@/modules/notifications/domain/service";
import type { OrderRepository } from "../infrastructure/repository";
import type { OrderDetails, OrderSummary } from "../types";
import { canTransitionOrder } from "./rules";
import { fulfillPaidDigitalItems } from "@/modules/digital/domain/service";

function errorFor(error: unknown): AppError { const code = error instanceof Error ? error.message : "ORDER_OPERATION_FAILED"; const messages: Record<string, string> = { CART_EMPTY: "Your cart is empty.", ADDRESS_NOT_FOUND: "Please select one of your saved addresses.", PAYMENT_METHOD_UNAVAILABLE: "This payment method is not available.", COD_NOT_ELIGIBLE_FOR_DIGITAL: "Cash on delivery is unavailable when digital products are in the cart.", DIGITAL_ASSET_UNAVAILABLE: "This digital product is temporarily unavailable until its file is configured.", PRODUCT_UNAVAILABLE: "One of the products in your cart is no longer available.", INSUFFICIENT_STOCK: "There is not enough stock for one of the products in your cart.", COUPON_PRICING_CHANGED: "Your coupon is no longer available at this price. Please review your updated order total.", SHIPPING_UNAVAILABLE: "Shipping is currently unavailable. Please try again later.", SHIPPING_CONFIGURATION_AMBIGUOUS: "Shipping is currently unavailable. Please try again later.", SHIPPING_RATE_INVALID: "Shipping is currently unavailable. Please try again later.", ADDRESS_MARKET_MISMATCH: "Please select a delivery address for the current market.", ORDER_NOT_FOUND: "The order does not exist.", ORDER_STATE_CHANGED: "The order was updated by another request. Please refresh and try again.", ORDER_TRANSITION_INVALID: "That order transition is not allowed for its payment or fulfillment state.", PAYMENT_TRANSITION_INVALID: "That payment transition is not allowed. Use the payment verification workflow.", DIGITAL_ORDER_NO_SHIPMENT: "Digital-only orders do not have a shipment workflow." }; return new AppError(code, messages[code] ?? "The order could not be completed.", { cause: error }); }
export class OrderService {
  constructor(private readonly repository: OrderRepository, private readonly authorization: AuthorizationService, private readonly notifications: NotificationService = createNotificationService()) {}
  async placeOrder(customerId: UserId, addressId: string | null | undefined, paymentMethodId: string, currency: string, checkoutToken: string, paymentReference?: string, paymentNotes?: string): Promise<Result<OrderDetails, AppError>> { try { return success(await this.repository.placeOrder(customerId, addressId ?? null, paymentMethodId, currency, checkoutToken, paymentReference, paymentNotes)); } catch (error) { return failure(errorFor(error)); } }
  async getCustomerOrders(customerId: UserId): Promise<Result<OrderSummary[], AppError>> { try { return success(await this.repository.findCustomerOrders(customerId)); } catch (error) { return failure(errorFor(error)); } }
  async getCustomerOrder(customerId: UserId, orderNumber: string): Promise<Result<OrderDetails, AppError>> { try { const order = await this.repository.findCustomerOrder(customerId, orderNumber); return order ? success(order) : failure(new NotFoundError("ORDER", "Order does not exist.")); } catch (error) { return failure(errorFor(error)); } }
  async getAdminOrders(userId: UserId): Promise<Result<OrderSummary[], AppError>> { const allowed = await this.authorization.requirePermission(userId, "orders.view"); if (!allowed.success) return failure(allowed.error); try { return success(await this.repository.findAdminOrders()); } catch (error) { return failure(errorFor(error)); } }
  async getAdminOrder(userId: UserId, orderId: string): Promise<Result<OrderDetails, AppError>> { const allowed = await this.authorization.requirePermission(userId, "orders.view"); if (!allowed.success) return failure(allowed.error); try { const order = await this.repository.findAdminOrder(orderId); return order ? success(order) : failure(new NotFoundError("ORDER", "Order does not exist.")); } catch (error) { return failure(errorFor(error)); } }
  async updateStatus(userId: UserId, orderId: string, status: OrderDetails["status"]): Promise<Result<OrderDetails, AppError>> { const allowed = await this.authorization.requirePermission(userId, "orders.update"); if (!allowed.success) return failure(allowed.error); try { const context = await this.repository.findTransitionContext(orderId); if (!context) return failure(new NotFoundError("ORDER", "Order does not exist.")); if (context.hasShipment && ["SHIPPED", "OUT_FOR_DELIVERY", "DELIVERED"].includes(status)) return failure(new ValidationError("Use the shipment workflow for physical delivery updates.")); if (!canTransitionOrder({ ...context, current: context.status, next: status })) throw new Error("ORDER_TRANSITION_INVALID"); const updated = await this.repository.updateStatus(orderId, context.status, status, userId); await this.notifyStatus(updated); return success(updated); } catch (error) { return failure(errorFor(error)); } }
  async updatePaymentStatus(userId: UserId, orderId: string, status: OrderDetails["paymentStatus"], note?: string): Promise<Result<OrderDetails, AppError>> { const current = await this.repository.findPaymentStatus(orderId); if (!current) return failure(new NotFoundError("ORDER", "Order does not exist.")); const verificationChange = ["PAID", "FAILED"].includes(status) && ["PENDING", "PENDING_VERIFICATION"].includes(current); const allowed = await this.authorization.requirePermission(userId, verificationChange ? "payments.verify" : "payments.update"); if (!allowed.success) return failure(allowed.error); if (current === status) return this.getAdminOrder(userId, orderId); if (!verificationChange) return failure(new ValidationError("Payment changes must use the trusted verification workflow.")); try { const updated = await this.repository.updatePaymentStatus(orderId, status, userId, note); if (status === "PAID") { try { await fulfillPaidDigitalItems(orderId); } catch (error) { logger.error("Paid digital fulfillment failed", { orderId, error }); } } if (status === "PAID" || status === "FAILED") await this.notifyPayment(updated, status); return success(updated); } catch (error) { return failure(errorFor(error)); } }
  private async notifyStatus(order: OrderDetails) { const result = await this.notifications.createOrderStatusNotification(order.customerId as UserId, order.id, order.orderNumber, order.status); if (!result.success) logger.warn("Customer order status notification was not created", { orderId: order.id, code: result.error.code }); }
  private async notifyPayment(order: OrderDetails, status: "PAID" | "FAILED") { const result = await this.notifications.createPaymentNotification(order.customerId as UserId, order.id, order.orderNumber, status); if (!result.success) logger.warn("Customer payment notification was not created", { orderId: order.id, code: result.error.code }); }
}
