"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createCatalogTaxonomy } from "../server/actions";

type Entry = { id: string; slug: string; nameAr: string; nameEn: string; isActive: boolean; sortOrder: number; minAgeMonths?: number; maxAgeMonths?: number; _count?: { products: number } };
type Props = { initial: { skills: Entry[]; objectives: Entry[]; productTypes: Entry[]; ageGroups: Entry[] } };
const sections = [{ key: "skill", label: "Skills", field: "skills" }, { key: "objective", label: "Learning objectives", field: "objectives" }, { key: "productType", label: "Product types", field: "productTypes" }, { key: "ageGroup", label: "Age groups", field: "ageGroups" }] as const;
export function AdminCatalogTaxonomyClient({ initial }: Props) {
  const [data, setData] = useState(initial); const [form, setForm] = useState({ kind: "skill" as typeof sections[number]["key"], slug: "", nameAr: "", nameEn: "", minAgeMonths: "", maxAgeMonths: "" }); const [error, setError] = useState("");
  async function create() { setError(""); const result = await createCatalogTaxonomy(form.kind, { slug: form.slug, nameAr: form.nameAr, nameEn: form.nameEn, ...(form.kind === "ageGroup" ? { minAgeMonths: Number(form.minAgeMonths), maxAgeMonths: Number(form.maxAgeMonths) } : {}) }); if (!result.success) { setError(result.error.message); return; } const field = sections.find((item) => item.key === form.kind)!.field; setData((current) => ({ ...current, [field]: [...current[field], result.data] })); setForm((current) => ({ ...current, slug: "", nameAr: "", nameEn: "", minAgeMonths: "", maxAgeMonths: "" })); }
  return <div className="space-y-8"><div><h1 className="text-2xl font-bold">Educational catalog taxonomies</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Add and organize educational vocabulary without a code change or migration.</p></div><section className="rounded-[var(--radius-xl)] border border-[var(--border)] bg-[var(--surface-card)] p-5"><div className="grid gap-3 md:grid-cols-5"><select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value as typeof form.kind })} className="h-10 rounded-md border border-[var(--border)] bg-[var(--surface)] px-3 text-sm">{sections.map((section) => <option key={section.key} value={section.key}>{section.label}</option>)}</select><Input placeholder="slug" value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /><Input placeholder="Arabic name" value={form.nameAr} onChange={(event) => setForm({ ...form, nameAr: event.target.value })} /><Input placeholder="English name" value={form.nameEn} onChange={(event) => setForm({ ...form, nameEn: event.target.value })} />{form.kind === "ageGroup" && <><Input type="number" placeholder="min months" value={form.minAgeMonths} onChange={(event) => setForm({ ...form, minAgeMonths: event.target.value })} /><Input type="number" placeholder="max months" value={form.maxAgeMonths} onChange={(event) => setForm({ ...form, maxAgeMonths: event.target.value })} /></>}<Button onClick={() => void create()}>Add taxonomy</Button></div>{error && <p role="alert" className="mt-3 text-sm text-[var(--destructive)]">{error}</p>}</section><div className="grid gap-5 lg:grid-cols-2">{sections.map((section) => <section key={section.key} className="rounded-[var(--radius-xl)] border border-[var(--border)] bg-[var(--surface-card)] p-5"><h2 className="text-lg font-bold">{section.label}</h2><div className="mt-4 space-y-2">{data[section.field].map((entry) => <div key={entry.id} className="flex items-center justify-between border-b border-[var(--border-subtle)] py-2 text-sm"><span><b>{entry.nameAr}</b><span className="ms-2 text-[var(--text-secondary)]">{entry.nameEn}</span></span><span className="text-xs text-[var(--text-muted)]">{entry._count?.products ?? 0} products · {entry.isActive ? "Active" : "Disabled"}</span></div>)}</div></section>)}</div></div>;
}
