"use server";
import "server-only";
import { revalidatePath } from "next/cache";
import { Prisma } from "@prisma/client";
import { failure, success } from "@/core/result";
import { ValidationError } from "@/core/errors";
import { requireAuthenticatedUser } from "@/modules/auth/server/queries";
import { AuthorizationService } from "@/modules/identity/domain/services";
import { PrismaPermissionRepository, PrismaUserRepository } from "@/modules/identity/infrastructure/repository";
import { generateUniqueSlug } from "@/lib/slug";
import { blogCategorySchema, blogIdSchema, blogPostSchema } from "../schema";
import { BlogRepository } from "../infrastructure/repository";

const repository = () => new BlogRepository();
const authorization = () => new AuthorizationService(new PrismaPermissionRepository(), new PrismaUserRepository());
async function permitted(permission: string) { const actor = await requireAuthenticatedUser(); if (!actor.success) return { actor: null, error: actor.error }; const allowed = await authorization().requirePermission(actor.data.user.id as never, permission); return allowed.success ? { actor: actor.data, error: null } : { actor: null, error: allowed.error }; }
function mapError(error: unknown) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return new ValidationError("That blog slug is already in use."); const code = error instanceof Error ? error.message : "BLOG_OPERATION_FAILED"; const messages: Record<string, string> = { BLOG_CATEGORY_INVALID: "Select a valid blog category.", BLOG_PRODUCT_INVALID: "One or more related products are unavailable.", BLOG_STORE_CATEGORY_INVALID: "One or more related store categories are unavailable.", BLOG_COVER_INVALID: "Select an existing image cover." }; return new ValidationError(messages[code] ?? "Blog content could not be saved."); }
export async function createBlogCategory(input: unknown) { const parsed = blogCategorySchema.safeParse(input); if (!parsed.success) return failure(new ValidationError("Please provide valid blog category details.")); const guard = await permitted("blog.categories"); if (guard.error) return failure(guard.error); try { const slug = await generateUniqueSlug(parsed.data.slug || parsed.data.nameEn, (candidate) => repository().findCategoryBySlug(candidate, false).then(Boolean)); return success(await repository().createCategory({ ...parsed.data, slug })); } catch (error) { return failure(mapError(error)); } }
export async function updateBlogCategory(input: unknown) { const raw = input as { id?: unknown }; const parsed = blogCategorySchema.safeParse(input); const id = blogIdSchema.safeParse(raw?.id); if (!parsed.success || !id.success) return failure(new ValidationError("Please provide valid blog category details.")); const guard = await permitted("blog.categories"); if (guard.error) return failure(guard.error); try { const slug = parsed.data.slug || parsed.data.nameEn.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); return success(await repository().updateCategory(id.data, { ...parsed.data, slug })); } catch (error) { return failure(mapError(error)); } }
export async function saveBlogPost(input: unknown) { const parsed = blogPostSchema.safeParse(input); if (!parsed.success) return failure(new ValidationError("Please review the article fields.")); const id = typeof (input as { id?: unknown })?.id === "string" ? (input as { id: string }).id : null; const guard = await permitted(parsed.data.status === "PUBLISHED" ? "blog.publish" : id ? "blog.update" : "blog.create"); if (guard.error) return failure(guard.error); try { const slug = parsed.data.slug || await generateUniqueSlug(parsed.data.titleEn, (candidate) => repository().findPublicBySlug(candidate).then(Boolean)); const post = id ? await repository().updatePost(id, { ...parsed.data, slug }) : await repository().createPost({ ...parsed.data, slug }); revalidatePath("/blog", "layout"); revalidatePath(`/blog/${post.slug}`, "page"); revalidatePath("/admin/blog", "layout"); return success(post); } catch (error) { return failure(mapError(error)); } }
export async function archiveBlogPost(id: string) { const valid = blogIdSchema.safeParse(id); if (!valid.success) return failure(new ValidationError("Select a valid article.")); const guard = await permitted("blog.delete"); if (guard.error) return failure(guard.error); try { const post = await repository().deletePost(valid.data); revalidatePath("/blog", "layout"); revalidatePath(`/blog/${post.slug}`, "page"); return success(true); } catch (error) { return failure(mapError(error)); } }
