export const userStatuses = [
  "ACTIVE",
  "INACTIVE",
  "SUSPENDED",
  "PENDING",
] as const;

export type UserStatus = (typeof userStatuses)[number];

export const userTypes = ["ADMIN", "CUSTOMER"] as const;

export type UserType = (typeof userTypes)[number];

export const systemRoles = [
  "ADMIN",
] as const;

export const defaultPermissionDefinitions = [
  { key: "admin.access", description: "Access the admin application." },
  { key: "dashboard.view", description: "View the admin dashboard." },
  { key: "products.view", description: "View products." },
  { key: "products.create", description: "Create products." },
  { key: "products.update", description: "Update products." },
  { key: "products.archive", description: "Archive and restore products." },
  { key: "products.delete", description: "Delete products." },
  { key: "categories.view", description: "View categories." },
  { key: "categories.create", description: "Create categories." },
  { key: "categories.update", description: "Update categories." },
  { key: "catalog.category.manage", description: "Manage the educational category tree." },
  { key: "catalog.taxonomy.manage", description: "Manage educational catalog taxonomies." },
  { key: "orders.view", description: "View orders." },
  { key: "orders.update", description: "Update orders." },
  { key: "payments.view", description: "View payment methods and payment status." },
  { key: "payments.update", description: "Update payment methods and payment status." },
  { key: "payments.verify", description: "Approve or reject manual payment verification." },
  { key: "payments.settle", description: "Settle collected cash-on-delivery payments." },
  { key: "payments.settings", description: "Configure store payment methods." },
  { key: "customers.view", description: "View customers." },
  { key: "customers.update", description: "Update customer status." },
  { key: "customers.export", description: "Export customer audience data." },
  { key: "inventory.view", description: "View inventory." },
  { key: "inventory.update", description: "Update product stock quantities." },
  { key: "shipping.view", description: "View shipping operations." },
  { key: "shipping.update", description: "Manage shipping companies, shipments, and returns." },
  { key: "users.view", description: "View users." },
  { key: "users.create", description: "Create administration users." },
  { key: "users.update", description: "Update administration users." },
  { key: "roles.view", description: "View roles and permissions." },
  { key: "roles.create", description: "Create custom administration roles." },
  { key: "roles.update", description: "Update roles and permissions." },
  { key: "roles.delete", description: "Delete custom administration roles." },
  { key: "reports.view", description: "View reports." },
  { key: "settings.view", description: "View store configuration." },
  { key: "settings.update", description: "Update store configuration." },
  { key: "audit.view", description: "View the administrator activity log." },
  { key: "media.view", description: "View uploaded store media." },
  { key: "media.upload", description: "Upload store images." },
  { key: "media.delete", description: "Delete unused store images." },
  { key: "promotions.view", description: "View promotions and offers." },
  { key: "promotions.create", description: "Create promotions and offers." },
  { key: "promotions.update", description: "Update promotions and offers." },
  { key: "promotions.delete", description: "Delete unused promotions." },
  { key: "coupons.view", description: "View coupons and usage history." },
  { key: "coupons.create", description: "Create coupon codes." },
  { key: "coupons.update", description: "Update coupon codes." },
  { key: "coupons.delete", description: "Delete unused coupon codes." },
  { key: "returns.view", description: "View customer return requests." },
  { key: "returns.manage", description: "Approve, reject, receive, and complete customer returns." },
  { key: "payments.refund", description: "Complete customer refunds." },
  { key: "reviews.view", description: "View customer product reviews." },
  { key: "reviews.moderate", description: "Approve or reject customer product reviews." },
] as const;

export const defaultRoleDefinitions = [
  {
    name: "ADMIN",
    description: "Administrative access to day-to-day operations.",
    permissions: [
      "admin.access",
      "dashboard.view",
      "products.view",
      "products.create",
      "products.update",
      "products.archive",
      "products.delete",
      "categories.view",
      "categories.create",
      "categories.update",
      "catalog.category.manage",
      "catalog.taxonomy.manage",
      "orders.view",
      "orders.update",
      "payments.view",
      "payments.update",
      "payments.verify",
      "payments.settle",
      "payments.settings",
      "customers.view",
      "customers.update",
      "customers.export",
      "inventory.view",
      "inventory.update",
      "shipping.view",
      "shipping.update",
      "users.view",
      "users.create",
      "users.update",
      "roles.view",
      "roles.create",
      "roles.update",
      "roles.delete",
      "reports.view",
      "settings.view",
      "settings.update",
      "audit.view",
      "media.view",
      "media.upload",
      "media.delete",
      "promotions.view",
      "promotions.create",
      "promotions.update",
      "promotions.delete",
      "coupons.view",
      "coupons.create",
      "coupons.update",
      "coupons.delete",
      "returns.view",
      "returns.manage",
      "payments.refund",
      "reviews.view",
      "reviews.moderate",
    ],
  },
] as const;

export const identityPermissionKeys = defaultPermissionDefinitions.map(
  ({ key }) => key,
);
