export const defaultStoreSettings = [
  { key: "store.name", value: "Maharat Kids" },
  { key: "store.currency", value: "SAR" },
  { key: "store.language", value: "ar" },
  { key: "store.email", value: "" },
  { key: "store.phone", value: "" },
  { key: "seo.title", value: "Maharat Kids | مهارة طفل" },
  { key: "seo.description", value: "Learning, play, and thoughtful tools for growing minds." },
  { key: "auth.google.enabled", value: false },
  { key: "promotions.maxActiveOffers", value: 10 },
  { key: "promotions.maxHeroOffers", value: 3 },
  { key: "returns.enabled", value: false },
  { key: "returns.windowDays", value: 14 },
  { key: "returns.policyText", value: "" },
] as const;
