import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { PrismaClient, ContentLocale, Market, ProductFulfillmentType, ProductLanguage, ProductStatus, DifficultyLevel, DigitalAssetStatus } from "@prisma/client";

const prisma = new PrismaClient();
const root = resolve(process.cwd());
const sourceImages = join(root, "seed-assets", "demo-source", "images");
const digitalDir = join(root, "seed-assets", "demo-source", "digital");
const mapPath = join(root, "seed-assets", "demo-catalog", "product-source-map.json");
const confirm = process.argv.includes("--confirm");
const clean = process.argv.includes("--clean");
let privateObjectStorage: typeof import("../src/modules/storage/provider")["privateObjectStorage"];

async function publicMediaFile(filename: string, sourceRoot: string, mimeType: string) {
  const bytes = await readFile(join(sourceRoot, filename));
  const key = `demo-catalog/${sourceRoot === sourceImages ? "products" : "digital-covers"}/${filename}`;
  const url = `/${key}`;
  const existing = await prisma.media.findFirst({ where: { path: key } });
  return existing ? prisma.media.update({ where: { id: existing.id }, data: { url, filename, mimeType, size: bytes.byteLength } }) : prisma.media.create({ data: { url, path: key, filename, mimeType, size: bytes.byteLength } });
}

async function coverMedia(filename: string) { return publicMediaFile(filename, join(digitalDir, "covers"), "image/png"); }

type DemoProduct = {
  slug: string; ar: string; en: string; category: string; images: number[]; type: string;
  skills: string[]; objectives: string[]; contexts: string[]; age: string; price: number; stock: number;
  pieces: number; difficulty: DifficultyLevel; cover?: string; digital?: { file: string; key: string };
};

const categoryNames: Record<string, [string, string]> = {
  "demo-flash-cards": ["بطاقات تعليمية", "Educational Flash Cards"],
  "demo-speech-language": ["التخاطب واللغة", "Speech & Language"],
  "demo-focus-attention": ["التركيز والانتباه", "Focus & Attention"],
  "demo-visual-perception": ["الإدراك البصري", "Visual Perception"],
  "demo-educational-games": ["ألعاب تعليمية", "Educational Games"],
  "demo-puzzles-matching": ["البازل والمطابقة", "Puzzles & Matching"],
  "demo-pre-writing": ["التهيئة قبل الكتابة", "Pre-Writing"],
  "demo-sensory-play": ["اللعب الحسي", "Sensory Play"],
  "demo-books": ["كتب وأنشطة", "Books & Activities"],
  "demo-digital-books": ["كتب رقمية", "Digital Books"],
};
// Representative visuals are intentionally explicit so a clean demo seed gives every
// homepage navigation category a credible image, including legacy categories with no products.
const categoryImageNumbers: Record<string, number> = {
  bundles: 57, fashion: 4, technology: 53, "educational-books": 49,
  "demo-flash-cards": 1, "educational-games": 47, "focus-attention": 63,
  "home-living": 5, "creative-play": 55, "sensory-integration": 33,
  "talking-language": 7, "demo-speech-language": 12, "demo-focus-attention": 63,
  "demo-visual-perception": 35, "demo-educational-games": 13,
  "demo-puzzles-matching": 14, "demo-pre-writing": 60, "demo-sensory-play": 33,
  "demo-books": 49, "demo-digital-books": 64,
};

const sourceGroups = [[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14,15],[16,17],[18,19],[20,21],[22,23],[24],[25,26],[27,28],[29,30],[31,32],[33,34],[35,36,37],[38,39,40],[41,42],[43,44],[45,46],[47,48],[49,50],[51,52],[53,54],[55,56],[57,58,59],[60,61,62],[63,64],[65,66],[67,68],[69,70]];
const catalogNames: [string, string][] = [
  ["بطاقات الفواكه والخضروات", "Fruits & Vegetables Flash Cards"], ["بطاقات الحيوانات", "Animal Flash Cards"], ["بطاقات الألوان والأشكال", "Colors & Shapes Flash Cards"], ["بطاقات الملابس", "Clothing Vocabulary Cards"], ["بطاقات المنزل", "Home Vocabulary Cards"], ["بطاقات المشاعر", "Feelings Cards"], ["مجموعة أدوات التخاطب", "Speech Starter Cards"], ["بطاقات الأفعال المصورة", "Action Cards"], ["بطاقات المهن", "Community Helpers Cards"], ["بطاقات العلاقات", "Associations Cards"], ["بطاقات المواصلات", "Transportation Cards"], ["بطاقات ماذا؟", "What? Question Cards"], ["لوحة الأنشطة اليومية", "Daily Activities Board"], ["لعبة المطابقة الأولى", "First Matching Game"], ["بطاقات أين؟", "Where? Concept Cards"], ["بطاقات التسلسل المصور", "Picture Sequencing Cards"], ["لعبة فرز المواصلات", "Transportation Sorting Game"], ["بطاقات الحيوانات وبيئاتها", "Animals & Habitats"], ["لعبة المطابقة والظل", "Shape & Shadow Match"], ["بطاقات المفاهيم الأساسية", "Basic Concepts Cards"], ["لعبة الروتين اليومي", "Daily Routine Game"], ["بازل التصنيف والأنماط", "Patterns & Sorting Puzzle"], ["مجموعة الحروف والأرقام", "Letters & Numbers Set"], ["حقيبة المرح الحسي", "Sensory Discovery Kit"], ["لعبة الإدراك البصري", "Visual Perception Game"], ["مجموعة الأنشطة المنزلية", "Home Learning Activities"], ["لعبة الخرز بالبطاقات", "Beads by Pattern Cards"], ["لوحة المهارات الحركية", "Fine Motor Skills Board"], ["بطاقات المشاعر والانفعالات", "Emotions & Expressions Cards"], ["لعبة الذاكرة التعليمية", "Educational Memory Game"], ["كتاب الأنشطة المصور", "Illustrated Activity Book"], ["لعبة الكلمات الأولى", "First Words Activity Kit"], ["لعبة Brain Gym للحركة", "Brain Gym Movement Kit"], ["لعبة التصنيف الذكي", "Smart Classification Game"], ["بازل خشبي متعدد القطع", "Multi-piece Wooden Puzzle"], ["مجموعة التهيئة قبل الكتابة", "Pre-Writing Practice Set"], ["كتاب الإدراك والمطابقة", "Perception & Matching Book"], ["لعبة الذاكرة المصورة", "Picture Memory Game"], ["لعبة المفتش الصغير", "Little Inspector Game"], ["لعبة السرعة والمطابقة", "Fast Match Game"],
];
const slugs = ["fruits-vegetables-flash-cards","animal-flash-cards","colors-shapes-flash-cards","clothing-vocabulary-cards","home-vocabulary-cards","feelings-cards","speech-starter-cards","action-cards","community-helpers-cards","associations-cards","transportation-cards","what-question-cards","daily-activities-board","first-matching-game","where-concept-cards","picture-sequencing-cards","transportation-sorting-game","animals-habitats","shape-shadow-match","basic-concepts-cards","daily-routine-game","patterns-sorting-puzzle","letters-numbers-set","sensory-discovery-kit","visual-perception-game","home-learning-activities","beads-pattern-cards","fine-motor-skills-board","emotions-expressions-cards","educational-memory-game","illustrated-activity-book","first-words-activity-kit","brain-gym-movement-kit","smart-classification-game","multi-piece-wooden-puzzle","pre-writing-practice-set","perception-matching-book","picture-memory-game","little-inspector-game","fast-match-game"];
const categories = ["demo-flash-cards","demo-flash-cards","demo-flash-cards","demo-flash-cards","demo-flash-cards","demo-flash-cards","demo-speech-language","demo-speech-language","demo-speech-language","demo-speech-language","demo-flash-cards","demo-speech-language","demo-educational-games","demo-puzzles-matching","demo-visual-perception","demo-visual-perception","demo-educational-games","demo-visual-perception","demo-puzzles-matching","demo-visual-perception","demo-educational-games","demo-puzzles-matching","demo-educational-games","demo-sensory-play","demo-visual-perception","demo-books","demo-educational-games","demo-pre-writing","demo-speech-language","demo-educational-games","demo-books","demo-speech-language","demo-educational-games","demo-educational-games","demo-puzzles-matching","demo-pre-writing","demo-books","demo-educational-games","demo-educational-games","demo-educational-games"];
const skills = ["focus-attention","visual-perception","auditory-perception","speech-language","vocabulary","matching","classification","logical-thinking","problem-solving","fine-motor","visual-motor","pre-writing","creativity","impulse-control","sensory-integration","visual-memory","expression"];
const objectives = ["sustain-attention","build-vocabulary","recognize-emotions","match-and-classify","follow-sequences","develop-fine-motor","prepare-for-writing","practice-concepts","encourage-language","remember-visual-details"];
const productTypes = ["flash-cards","educational-book","puzzle","educational-game","speech-tool","sensory-activity","learning-aid","activity-kit","educational-board","coloring-activity","bundle","digital-book"];
const contexts = ["home","nursery","school","speech-center","individual","group"];
const ages: ReadonlyArray<readonly [string, number, number, string, string]> = [["6m-2y",6,24,"من 6 أشهر إلى سنتين","6 months–2 years"],["3-6y",36,72,"من 3 إلى 6 سنوات","3–6 years"],["6-12y",72,144,"من 6 إلى 12 سنة","6–12 years"]];

const products: DemoProduct[] = catalogNames.map(([ar, en], i) => ({
  slug: slugs[i], ar, en, category: categories[i], images: sourceGroups[i],
  type: i < 12 ? "flash-cards" : i % 7 === 0 ? "puzzle" : i % 5 === 0 ? "activity-kit" : "educational-game",
  skills: [skills[i % skills.length], skills[(i + 3) % skills.length]],
  objectives: [objectives[i % objectives.length], objectives[(i + 4) % objectives.length]],
  contexts: [contexts[i % contexts.length], contexts[(i + 1) % contexts.length]],
  age: i < 6 ? "3-6y" : i % 6 === 0 ? "6-12y" : "3-6y", price: 49 + (i % 8) * 20, stock: 8 + (i * 7) % 43,
  pieces: 12 + (i % 5) * 6, difficulty: i % 5 === 0 ? DifficultyLevel.INTERMEDIATE : DifficultyLevel.BEGINNER,
}));
products.push(
  { slug: "demo-digital-attention-focus", ar: "كتاب أنشطة التركيز والانتباه", en: "Attention & Focus Activity Book", category: "demo-digital-books", images: [], cover: "attention-focus-01.png", type: "digital-book", skills: ["focus-attention","visual-memory"], objectives: ["sustain-attention","remember-visual-details"], contexts: ["home","individual"], age: "3-6y", price: 29, stock: 0, pieces: 1, difficulty: DifficultyLevel.BEGINNER, digital: { file: "attention-focus-activity-book.pdf", key: "digital-assets/00000000-0000-4000-8000-000000000001/attention-focus.pdf" } },
  { slug: "demo-digital-pre-writing", ar: "كراسة التهيئة قبل الكتابة", en: "Pre-Writing Skills Workbook", category: "demo-digital-books", images: [], cover: "pre-writing-01.png", type: "digital-book", skills: ["pre-writing","fine-motor"], objectives: ["prepare-for-writing","develop-fine-motor"], contexts: ["home","school"], age: "3-6y", price: 32, stock: 0, pieces: 1, difficulty: DifficultyLevel.BEGINNER, digital: { file: "pre-writing-skills-workbook.pdf", key: "digital-assets/00000000-0000-4000-8000-000000000002/pre-writing.pdf" } },
  { slug: "demo-digital-visual-matching", ar: "كتاب الإدراك البصري والمطابقة", en: "Visual Perception & Matching Workbook", category: "demo-digital-books", images: [], cover: "visual-matching-01.png", type: "digital-book", skills: ["visual-perception","matching"], objectives: ["match-and-classify","remember-visual-details"], contexts: ["home","speech-center"], age: "3-6y", price: 32, stock: 0, pieces: 1, difficulty: DifficultyLevel.BEGINNER, digital: { file: "visual-perception-matching-workbook.pdf", key: "digital-assets/00000000-0000-4000-8000-000000000003/visual-matching.pdf" } },
  { slug: "demo-digital-basic-concepts", ar: "بطاقات المفاهيم الأساسية المصورة", en: "Basic Concepts Activity Book", category: "demo-digital-books", images: [], cover: "basic-concepts-01.png", type: "digital-book", skills: ["vocabulary","visual-perception"], objectives: ["practice-concepts","build-vocabulary"], contexts: ["home","nursery"], age: "3-6y", price: 29, stock: 0, pieces: 1, difficulty: DifficultyLevel.BEGINNER, digital: { file: "basic-concepts-activity-book.pdf", key: "digital-assets/00000000-0000-4000-8000-000000000004/basic-concepts.pdf" } },
);

function requireSafeMode() {
  if (!confirm) throw new Error("Refusing demo catalog mutation without --confirm.");
  if (process.env.NODE_ENV === "production") throw new Error("Demo catalog seed is disabled in production.");
  if (process.env.NODE_ENV !== "development" && process.env.NODE_ENV !== "test") throw new Error("Set NODE_ENV=development or NODE_ENV=test for demo catalog seed.");
}
function ageInfo(slug: string) { const age = ages.find((a) => a[0] === slug) ?? ages[1]; return { minAgeMonths: age[1], maxAgeMonths: age[2], nameAr: age[3], nameEn: age[4] }; }
async function taxonomy() {
  for (const [i, slug] of skills.entries()) await prisma.skill.upsert({ where: { slug }, update: {}, create: { slug, nameAr: ["التركيز والانتباه","الإدراك البصري","الإدراك السمعي","التخاطب واللغة","المفردات","المطابقة","التصنيف","التفكير المنطقي","حل المشكلات","المهارات الحركية الدقيقة","التآزر البصري الحركي","التهيئة للكتابة","الإبداع","ضبط الاندفاع","التكامل الحسي","الذاكرة البصرية","التعبير"][i], nameEn: slug.replaceAll("-", " "), sortOrder: i } });
  for (const [i, slug] of objectives.entries()) await prisma.learningObjective.upsert({ where: { slug }, update: {}, create: { slug, nameAr: ["إطالة مدة الانتباه","بناء المفردات","التعرف على المشاعر","المطابقة والتصنيف","اتباع التسلسل","تطوير المهارات الدقيقة","الاستعداد للكتابة","التدرب على المفاهيم","تشجيع اللغة","تذكر التفاصيل البصرية"][i], nameEn: slug.replaceAll("-", " "), sortOrder: i } });
  for (const [i, slug] of productTypes.entries()) await prisma.productType.upsert({ where: { slug }, update: {}, create: { slug, nameAr: slug.replaceAll("-", " "), nameEn: slug.replaceAll("-", " "), sortOrder: i } });
  for (const [i, slug] of contexts.entries()) await prisma.useContext.upsert({ where: { slug }, update: {}, create: { slug, nameAr: slug.replaceAll("-", " "), nameEn: slug.replaceAll("-", " "), sortOrder: i } });
  for (const [i, [slug, min, max, ar, en]] of ages.entries()) await prisma.ageGroup.upsert({ where: { slug }, update: { minAgeMonths: min, maxAgeMonths: max }, create: { slug, minAgeMonths: min, maxAgeMonths: max, nameAr: ar, nameEn: en, sortOrder: i } });
}
async function categoriesSeed() { for (const [sortOrder, [slug, [nameAr, nameEn]]] of Object.entries(categoryNames).map(([slug, names], i) => [i, [slug, names]] as const)) { const category = await prisma.category.upsert({ where: { slug }, update: { name: nameEn, isActive: true, showInNavigation: true, sortOrder }, create: { slug, name: nameEn, isActive: true, showInNavigation: true, sortOrder } }); const representative = await mediaFor(categoryImageNumbers[slug]); await prisma.category.update({ where: { id: category.id }, data: { imageMediaId: representative.id, imageUrl: null } }); await prisma.categoryTranslation.upsert({ where: { categoryId_locale: { categoryId: category.id, locale: ContentLocale.ar } }, update: { name: nameAr }, create: { categoryId: category.id, locale: ContentLocale.ar, name: nameAr } }); await prisma.categoryTranslation.upsert({ where: { categoryId_locale: { categoryId: category.id, locale: ContentLocale.en } }, update: { name: nameEn }, create: { categoryId: category.id, locale: ContentLocale.en, name: nameEn } }); for (const slug of Object.keys(categoryImageNumbers)) { if (Object.hasOwn(categoryNames, slug)) continue; const existing = await prisma.category.findUnique({ where: { slug } }); if (existing) { const representative = await mediaFor(categoryImageNumbers[slug]); await prisma.category.update({ where: { id: existing.id }, data: { imageMediaId: representative.id, imageUrl: null } }); } } }
}
async function mediaFor(number: number) { const filename = `client-${String(number).padStart(3, "0")}.jpg`; const bytes = await readFile(join(sourceImages, filename)); const key = `demo-catalog/products/${filename}`; const url = `/${key}`; const old = await prisma.media.findFirst({ where: { path: key } }); return old ? prisma.media.update({ where: { id: old.id }, data: { url, filename, mimeType: "image/jpeg", size: bytes.byteLength } }) : prisma.media.create({ data: { url, path: key, filename, mimeType: "image/jpeg", size: bytes.byteLength } }); }
async function seedProduct(item: DemoProduct, index: number) {
  const cat = await prisma.category.findUniqueOrThrow({ where: { slug: item.category } }); const age = ageInfo(item.age); const price = item.price; const product = await prisma.product.upsert({ where: { slug: `demo-${item.slug}` }, update: { name: item.en, shortDescription: `A practical Maharat Kids activity for ${item.en.toLowerCase()}.`, description: `A realistic demo catalog item with guided play instructions and safe, screen-free practice.`, price, compareAtPrice: price + 15, status: ProductStatus.ACTIVE, fulfillmentType: item.digital ? ProductFulfillmentType.DIGITAL : ProductFulfillmentType.PHYSICAL, categoryId: cat.id, primaryCategoryId: cat.id, minAgeMonths: age.minAgeMonths, maxAgeMonths: age.maxAgeMonths, difficultyLevel: item.difficulty, productLanguage: ProductLanguage.BILINGUAL, materials: item.digital ? "PDF download" : "Printed cards, board, and activity pieces", numberOfPieces: item.pieces, dimensions: item.digital ? "PDF" : "24 × 18 cm", recommendedPlayers: "1–4", supervisionRequired: true, safetyNotes: "Use with age-appropriate supervision. Not a medical treatment.", usageInstructions: "Choose a short activity, model it once, then let the child try.", trackInventory: !item.digital, stockQuantity: item.digital ? 0 : item.stock }, create: { slug: `demo-${item.slug}`, sku: `MK-DEMO-${String(index + 1).padStart(2, "0")}-${item.slug.toUpperCase().replaceAll("-", "_")}`, name: item.en, shortDescription: `A practical Maharat Kids activity for ${item.en.toLowerCase()}.`, description: `A realistic demo catalog item with guided play instructions and safe, screen-free practice.`, price, compareAtPrice: price + 15, status: ProductStatus.ACTIVE, fulfillmentType: item.digital ? ProductFulfillmentType.DIGITAL : ProductFulfillmentType.PHYSICAL, categoryId: cat.id, primaryCategoryId: cat.id, minAgeMonths: age.minAgeMonths, maxAgeMonths: age.maxAgeMonths, difficultyLevel: item.difficulty, productLanguage: ProductLanguage.BILINGUAL, materials: item.digital ? "PDF download" : "Printed cards, board, and activity pieces", numberOfPieces: item.pieces, dimensions: item.digital ? "PDF" : "24 × 18 cm", recommendedPlayers: "1–4", supervisionRequired: true, safetyNotes: "Use with age-appropriate supervision. Not a medical treatment.", usageInstructions: "Choose a short activity, model it once, then let the child try.", trackInventory: !item.digital, stockQuantity: item.digital ? 0 : item.stock } });
  await prisma.productMarketPrice.upsert({ where: { productId_market: { productId: product.id, market: Market.SAUDI_ARABIA } }, update: { price, compareAtPrice: price + 15 }, create: { productId: product.id, market: Market.SAUDI_ARABIA, price, compareAtPrice: price + 15 } }); await prisma.productMarketPrice.upsert({ where: { productId_market: { productId: product.id, market: Market.EGYPT } }, update: { price: Math.round(price * 13), compareAtPrice: Math.round((price + 15) * 13) }, create: { productId: product.id, market: Market.EGYPT, price: Math.round(price * 13), compareAtPrice: Math.round((price + 15) * 13) } });
  await prisma.productTranslation.upsert({ where: { productId_locale: { productId: product.id, locale: ContentLocale.ar } }, update: { name: item.ar, shortDescription: "نشاط تعليمي عملي للعب والتعلم في المنزل أو المركز.", description: "منتج تجريبي واقعي بتعليمات لعب واضحة ومحتوى مناسب للأطفال." }, create: { productId: product.id, locale: ContentLocale.ar, name: item.ar, shortDescription: "نشاط تعليمي عملي للعب والتعلم في المنزل أو المركز.", description: "منتج تجريبي واقعي بتعليمات لعب واضحة ومحتوى مناسب للأطفال." } }); await prisma.productTranslation.upsert({ where: { productId_locale: { productId: product.id, locale: ContentLocale.en } }, update: { name: item.en }, create: { productId: product.id, locale: ContentLocale.en, name: item.en, shortDescription: `A practical activity for ${item.en.toLowerCase()}.`, description: "A realistic demo product with guided, screen-free play." } });
  await prisma.productCategory.deleteMany({ where: { productId: product.id } }); await prisma.productCategory.create({ data: { productId: product.id, categoryId: cat.id } }); await prisma.productSkill.deleteMany({ where: { productId: product.id } }); await prisma.productLearningObjective.deleteMany({ where: { productId: product.id } }); await prisma.productProductType.deleteMany({ where: { productId: product.id } }); await prisma.productUseContext.deleteMany({ where: { productId: product.id } }); await prisma.productAgeGroup.deleteMany({ where: { productId: product.id } });
  for (const slug of item.skills) await prisma.productSkill.create({ data: { productId: product.id, skillId: (await prisma.skill.findUniqueOrThrow({ where: { slug } })).id } }); for (const slug of item.objectives) await prisma.productLearningObjective.create({ data: { productId: product.id, learningObjectiveId: (await prisma.learningObjective.findUniqueOrThrow({ where: { slug } })).id } }); await prisma.productProductType.create({ data: { productId: product.id, productTypeId: (await prisma.productType.findUniqueOrThrow({ where: { slug: item.type } })).id } }); for (const slug of item.contexts) await prisma.productUseContext.create({ data: { productId: product.id, useContextId: (await prisma.useContext.findUniqueOrThrow({ where: { slug } })).id } }); await prisma.productAgeGroup.create({ data: { productId: product.id, ageGroupId: (await prisma.ageGroup.findUniqueOrThrow({ where: { slug: item.age } })).id } });
  await prisma.productImage.deleteMany({ where: { productId: product.id } }); for (const [sortOrder, number] of item.images.entries()) { const media = await mediaFor(number); await prisma.productImage.create({ data: { productId: product.id, mediaId: media.id, url: media.url, altText: `${item.en} — ${sortOrder + 1}`, sortOrder, isPrimary: sortOrder === 0 } }); }
  if (item.digital) { const bytes = await readFile(join(digitalDir, item.digital.file)); if (!bytes.subarray(0, 5).equals(Buffer.from("%PDF-"))) throw new Error(`Invalid PDF: ${item.digital.file}`); if (!(await privateObjectStorage.exists(item.digital.key))) await privateObjectStorage.put({ key: item.digital.key, bytes, mimeType: "application/pdf" }); await prisma.digitalAsset.upsert({ where: { storageKey: item.digital.key }, update: { productId: product.id, displayNameAr: item.ar, displayNameEn: item.en, mimeType: "application/pdf", sizeBytes: bytes.byteLength, checksum: createHash("sha256").update(bytes).digest("hex"), version: 1, status: DigitalAssetStatus.ACTIVE }, create: { productId: product.id, displayNameAr: item.ar, displayNameEn: item.en, storageKey: item.digital.key, mimeType: "application/pdf", sizeBytes: bytes.byteLength, checksum: createHash("sha256").update(bytes).digest("hex"), version: 1, status: DigitalAssetStatus.ACTIVE } }); }
  return product;
}
async function variants(product: DemoProduct) { if (product.cover) { const productRow = await prisma.product.findUniqueOrThrow({ where: { slug: "demo-" + product.slug } }); const cover = await coverMedia(product.cover); await prisma.productImage.create({ data: { productId: productRow.id, mediaId: cover.id, url: cover.url, altText: product.en, sortOrder: 0, isPrimary: true } }); } if (!["letters-numbers-set", "first-matching-game"].includes(product.slug)) return; const p = await prisma.product.findUniqueOrThrow({ where: { slug: `demo-${product.slug}` } }); const oldVariants = await prisma.productVariant.findMany({ where: { productId: p.id }, select: { id: true } }); await prisma.productVariantMarketPrice.deleteMany({ where: { variantId: { in: oldVariants.map((v) => v.id) } } }); await prisma.productVariantOptionValue.deleteMany({ where: { variantId: { in: oldVariants.map((v) => v.id) } } }); await prisma.productVariant.deleteMany({ where: { productId: p.id } }); await prisma.productOption.deleteMany({ where: { productId: p.id } }); const option = await prisma.productOption.create({ data: { productId: p.id, nameAr: product.slug === "letters-numbers-set" ? "اللغة" : "حجم المجموعة", nameEn: product.slug === "letters-numbers-set" ? "Language" : "Pack size" } }); const labels = product.slug === "letters-numbers-set" ? [["عربي","Arabic"],["إنجليزي","English"]] : [["صغيرة","Small"],["كاملة","Complete"]]; for (const [i, [ar, en]] of labels.entries()) { const value = await prisma.productOptionValue.create({ data: { optionId: option.id, labelAr: ar, labelEn: en, sortOrder: i } }); const variant = await prisma.productVariant.create({ data: { productId: p.id, sku: `MK-DEMO-${product.slug.toUpperCase().replaceAll("-", "_")}-${i + 1}`, active: true, isDefault: i === 0, sortOrder: i, trackInventory: true, stockQuantity: 8 + i * 4, combinationKey: `${option.id}:${value.id}` } }); await prisma.productVariantOptionValue.create({ data: { variantId: variant.id, optionValueId: value.id } }); for (const [market, multiplier] of [[Market.SAUDI_ARABIA, 1 + i * 0.12], [Market.EGYPT, 13 + i]] as const) await prisma.productVariantMarketPrice.create({ data: { variantId: variant.id, market, price: Math.round(Number(product.price) * multiplier), compareAtPrice: Math.round((Number(product.price) + 15) * multiplier) } }); } }
async function writeSourceMap() { await mkdir(join(root, "seed-assets", "demo-catalog"), { recursive: true }); const map = products.map((p) => ({ slug: "demo-" + p.slug, sourceType: p.cover ? "ORIGINAL_DIGITAL_PDF_COVER" : "CLIENT_PROVIDED_PDF", sourceImages: p.images.map((n) => "client-" + String(n).padStart(3, "0") + ".jpg"), ...(p.cover ? { publicCover: "demo-catalog/digital-covers/" + p.cover } : {}), ...(p.digital ? { digitalAsset: p.digital.file } : {}) })); await writeFile(mapPath, JSON.stringify({ products: map }, null, 2)); }
async function cleanDemo() { const demo = await prisma.product.findMany({ where: { sku: { startsWith: "MK-DEMO-" } }, select: { id: true, slug: true } }); const orderCount = await prisma.orderItem.count({ where: { productId: { in: demo.map((p) => p.id) } } }); if (orderCount) throw new Error(`Refusing cleanup: ${orderCount} order item(s) reference demo products.`); const assets = await prisma.digitalAsset.findMany({ where: { productId: { in: demo.map((p) => p.id) } }, select: { id: true, storageKey: true } }); for (const asset of assets) { await privateObjectStorage.delete(asset.storageKey); await prisma.digitalAsset.delete({ where: { id: asset.id } }); } const mediaIds = (await prisma.productImage.findMany({ where: { productId: { in: demo.map((p) => p.id) } }, select: { mediaId: true } })).map((x) => x.mediaId).filter((x): x is string => Boolean(x)); await prisma.product.deleteMany({ where: { id: { in: demo.map((p) => p.id) } } }); for (const id of mediaIds) { const media = await prisma.media.findUnique({ where: { id } }); if (!media || !media.path.startsWith("demo-catalog/")) continue; const refs = await prisma.productImage.count({ where: { mediaId: id } }); if (!refs) await prisma.media.delete({ where: { id } }); } for (const slug of Object.keys(categoryNames)) { const category = await prisma.category.findUnique({ where: { slug } }); if (category && !(await prisma.productCategory.count({ where: { categoryId: category.id } }))) { await prisma.categoryTranslation.deleteMany({ where: { categoryId: category.id } }); await prisma.category.delete({ where: { id: category.id } }); } } console.log(`Cleaned ${demo.length} demo products.`); }
async function main() { requireSafeMode(); ({ privateObjectStorage } = await import("../src/modules/storage/provider")); if (clean) { await cleanDemo(); return; } if (!existsSync(sourceImages) || !existsSync(digitalDir)) throw new Error("Demo source assets are missing."); await taxonomy(); await categoriesSeed(); for (const [index, item] of products.entries()) { await seedProduct(item, index); await variants(item); } await writeSourceMap(); console.log(JSON.stringify({ physicalProducts: 40, digitalProducts: 4, sourceImages: 70, digitalPdfs: 4, sourceMap: mapPath }, null, 2)); }
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
