'use server';

import "server-only";

import { revalidatePath } from "next/cache";
import { ValidationError } from "@/core/errors";
import { failure } from "@/core/result";
import { requireAuthenticatedUser } from "@/modules/auth/server/queries";
import { AuthorizationService } from "@/modules/identity/domain/services";
import { PrismaPermissionRepository, PrismaUserRepository } from "@/modules/identity/infrastructure/repository";
import { adjustProductStockSchema, createProductSchema, productIdSchema, updateProductSchema } from "../schema";
import { ProductService } from "../domain/service";
import { PrismaProductRepository } from "../infrastructure/repository";
import { createMediaService } from "@/modules/media/server/service";
import { AUDIT_ACTIONS, AUDIT_ENTITY_TYPES } from "@/modules/audit/constants";
import { writeAdminAudit } from "@/modules/audit/server/writer";
import type { Product } from "../types";

function service() { return new ProductService(new PrismaProductRepository(), new AuthorizationService(new PrismaPermissionRepository(), new PrismaUserRepository()), createMediaService()); }
function hasProductChanges(input: { name: string; shortDescription?: string | null; description?: string | null; sku?: string | null; price: string; compareAtPrice?: string | null; status?: Product["status"]; isFeatured?: boolean; categoryId?: string | null; trackInventory?: boolean; stockQuantity?: number; images?: Array<{ mediaId: string; altText?: string | null; sortOrder?: number; isPrimary?: boolean }> }, product: Product) {
  if (input.name.trim() !== product.name || (input.shortDescription ?? null) !== product.shortDescription || (input.description ?? null) !== product.description || (input.sku ?? null) !== product.sku || input.price !== product.price || (input.compareAtPrice ?? null) !== product.compareAtPrice || (input.status ?? "DRAFT") !== product.status || (input.isFeatured ?? false) !== product.isFeatured || (input.categoryId ?? null) !== product.categoryId || (input.trackInventory ?? false) !== product.trackInventory || (input.stockQuantity ?? 0) !== product.stockQuantity) return true;
  const images = input.images ?? [];
  return images.length !== product.images.length || images.some((image, index) => {
    const current = product.images[index];
    return !current || image.mediaId !== current.mediaId || (image.altText ?? null) !== current.altText || (image.sortOrder ?? 0) !== current.sortOrder || (image.isPrimary ?? false) !== current.isPrimary;
  });
}
export async function createProduct(input: unknown) { const parsed = createProductSchema.safeParse(input); if (!parsed.success) return failure(new ValidationError("Please review the product details.", { issues: parsed.error.issues })); const actor = await requireAuthenticatedUser(); if (!actor.success) return failure(actor.error); const result = await service().create(actor.data.user.id, parsed.data); if (result.success) { await writeAdminAudit(actor.data, { action: AUDIT_ACTIONS.PRODUCT_CREATED, entityType: AUDIT_ENTITY_TYPES.PRODUCT, entityId: result.data.id, entityLabel: result.data.name }); revalidatePath("/admin/products"); revalidatePath("/products", "layout"); revalidatePath("/", "layout"); } return result; }
export async function updateProduct(input: unknown) { const parsed = updateProductSchema.safeParse(input); if (!parsed.success) return failure(new ValidationError("Please review the product details.", { issues: parsed.error.issues })); const actor = await requireAuthenticatedUser(); if (!actor.success) return failure(actor.error); const result = await service().update(actor.data.user.id, parsed.data); if (result.success) { if (hasProductChanges(parsed.data, result.data)) await writeAdminAudit(actor.data, { action: AUDIT_ACTIONS.PRODUCT_UPDATED, entityType: AUDIT_ENTITY_TYPES.PRODUCT, entityId: result.data.id, entityLabel: result.data.name }); revalidatePath("/admin/products"); revalidatePath("/products", "layout"); revalidatePath("/", "layout"); } return result; }
export async function setProductStatus(input: unknown) { const parsed = updateProductSchema.pick({ id: true, status: true }).safeParse(input); if (!parsed.success || !parsed.data.status || !["ACTIVE", "ARCHIVED"].includes(parsed.data.status)) return failure(new ValidationError("Please select a valid product status.")); const actor = await requireAuthenticatedUser(); if (!actor.success) return failure(actor.error); const result = await service().setStatus(actor.data.user.id, parsed.data.id, parsed.data.status as "ACTIVE" | "ARCHIVED"); if (result.success) { await writeAdminAudit(actor.data, { action: parsed.data.status === "ARCHIVED" ? AUDIT_ACTIONS.PRODUCT_ARCHIVED : AUDIT_ACTIONS.PRODUCT_RESTORED, entityType: AUDIT_ENTITY_TYPES.PRODUCT, entityId: result.data.id, entityLabel: result.data.name, changes: { fields: [{ field: "status", before: parsed.data.status === "ARCHIVED" ? "ACTIVE" : "ARCHIVED", after: parsed.data.status }] } }); revalidatePath("/admin/products"); revalidatePath("/products", "layout"); revalidatePath("/", "layout"); } return result; }
export async function duplicateProduct(input: unknown) { const parsed = productIdSchema.safeParse((input as { id?: unknown })?.id); if (!parsed.success) return failure(new ValidationError("Please select a valid product.")); const actor = await requireAuthenticatedUser(); if (!actor.success) return failure(actor.error); const result = await service().duplicate(actor.data.user.id, parsed.data); if (result.success) { await writeAdminAudit(actor.data, { action: AUDIT_ACTIONS.PRODUCT_CREATED, entityType: AUDIT_ENTITY_TYPES.PRODUCT, entityId: result.data.id, entityLabel: result.data.name, metadata: { duplicated: true } }); revalidatePath("/admin/products"); revalidatePath("/products", "layout"); } return result; }
export async function deleteProduct(input: unknown) { const parsed = productIdSchema.safeParse((input as { id?: unknown })?.id); if (!parsed.success) return failure(new ValidationError("Please select a valid product.")); const actor = await requireAuthenticatedUser(); if (!actor.success) return failure(actor.error); const result = await service().remove(actor.data.user.id, parsed.data); if (result.success) { await writeAdminAudit(actor.data, { action: AUDIT_ACTIONS.PRODUCT_DELETED, entityType: AUDIT_ENTITY_TYPES.PRODUCT, entityId: result.data.id, entityLabel: result.data.name }); revalidatePath("/admin/products"); revalidatePath("/products", "layout"); revalidatePath("/", "layout"); } return result; }
export async function adjustProductStock(input: unknown) { const parsed = adjustProductStockSchema.safeParse(input); if (!parsed.success) return failure(new ValidationError("Please enter a valid stock adjustment.")); const actor = await requireAuthenticatedUser(); if (!actor.success) return failure(actor.error); const result = await service().adjustStock(actor.data.user.id, parsed.data.id, parsed.data.quantityDelta, { actor: { userId: actor.data.user.id, name: actor.data.user.name, email: actor.data.user.email } }); if (result.success) { revalidatePath("/admin/products"); } return result; }
