import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale, type Locale } from "@/config/locale";
import { localizedAlternates, localizedUrl } from "@/lib/seo";
import { getPublicBlogCategories, getPublicBlogPosts } from "@/modules/blog/server/queries";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale: raw, slug } = await params; const locale: Locale = isLocale(raw) ? raw : "ar"; const categories = await getPublicBlogCategories(); const category = categories.success ? categories.data.find((item) => item.slug === slug) : null; if (!category) return {}; const title = locale === "ar" ? category.nameAr : category.nameEn; return { title, alternates: localizedAlternates(`/blog/category/${slug}`, locale), openGraph: { url: localizedUrl(`/blog/category/${slug}`, locale), type: "website" } }; }
export default async function BlogCategoryPage({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale: raw, slug } = await params; const locale: Locale = isLocale(raw) ? raw : "ar"; const [categories, posts] = await Promise.all([getPublicBlogCategories(), getPublicBlogPosts(slug)]); if (!categories.success) throw categories.error; if (!posts.success) throw posts.error; const category = categories.data.find((item) => item.slug === slug); if (!category) notFound(); return <div className="space-y-8"><header><Link href={`/${locale}/blog`} className="text-xs font-semibold text-[var(--primary)]">← {locale === "ar" ? "كل المقالات" : "All articles"}</Link><h1 className="mt-4 text-4xl font-black">{locale === "ar" ? category.nameAr : category.nameEn}</h1></header><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{posts.data.items.map((post) => <Link key={post.id} href={`/${locale}/blog/${post.slug}`} className="rounded-lg border border-[var(--border)] bg-[var(--surface-card)] p-5 hover:border-[var(--primary)]"><h2 className="font-bold">{locale === "ar" ? post.titleAr : post.titleEn}</h2><p className="mt-2 line-clamp-3 text-sm text-[var(--text-secondary)]">{locale === "ar" ? post.excerptAr : post.excerptEn}</p></Link>)}</div></div>; }
